services:
  - type: web
    name: jvl-backend
    runtime: python311
    buildCommand: "pip install -r backend/requirements.txt && python backend/manage.py migrate && python backend/manage.py collectstatic --noinput"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT backend.config.wsgi:application"
    rootDir: ""
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ALLOWED_HOSTS
        value: "jvl-backend.onrender.com,localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://JorgeFreire95.github.io,http://localhost:5175"

  - type: pserv
    name: jvl-db
    runtime: postgres15
    ipAllowList: []
