[build]
  command = "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
  runtime = "python-3.11"

[env]
  PYTHONUNBUFFERED = "1"
  DEBUG = "False"
  SECRET_KEY = ""
  ALLOWED_HOSTS = "jvl-backend.up.railway.app,localhost"
  CORS_ALLOWED_ORIGINS = "https://JorgeFreire95.github.io,http://localhost:5174"
